#!/bin/bash
#
# Plot analyzed SNVs and indels.

echo ""
echo "SNVs and indels plots"
echo ""

# Get scripts directory; supports symlinks
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"


if [[ $# -lt 1 ]]; then
  echo "snvs_indels_plot: need to provide arguments. see -h or --help."
  exit
fi
if [[ $# -lt 2 && "$1" != "-h" && "$1" != "--help" ]]; then
  echo "snvs_indels_plot: need to provide arguments. see -h or --help."
  exit
fi


while [[ $# -gt 1 || "$1" == "-h" || "$1" == "--help" ]]
do
  key="$1"
  case $key in
    -i|--input) # Input FASTA file with processed / qc'ed reads
    input_blast_table="$2"
    shift # past argument
    ;;
    -s|--input-snvs-indels) 
    input_snvs_indels="$2"
    shift
    ;;
    -e|--input-exons-fasta) 
    input_exons_fasta="$2"
    shift
    ;;
    -f|--input-fads)
	input_fads="$2"
	shift
	;;
    -o|--output-circoplot)
	output_circo="$2"
	shift
	;;
	--plot-abeta-region)
    plot_abeta="$2"
    shift
    ;;
    --del-intermediate-files) # Delete all intermediate files?
    del_files="$2"
    shift
    ;;
    -h|--help) # Show program usage
    cat $DIR/manuals/snvs_indels_plot.txt | more
    exit
    shift
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
    echo "blast_reads: unknown argument $key"
    # unknown option
    ;;
  esac
  shift # past argument or value
done

if [ -z "$del_files" ]; then
  del_files=1
fi
if [ -z "$plot_abeta" ]; then
  plot_abeta=1
fi

if [ -z "$input_fads" ]; then
  input_fads=""
else
  input_fads="--input-fads ${input_fads}"
fi

echo -n "* Generating exon lengths..."
output_exon_lengths="${input_exons_fasta%.*}_exon_lengths.txt"
$DIR/generate_exon_lengths $input_exons_fasta $output_exon_lengths
echo " OK."

Rscript --vanilla $DIR/plot_circo_snv_indel.R \
    --input-exon-table $input_blast_table \
    --input-snvs-indels $input_snvs_indels \
    $input_fads \
    --input-exon-lengths $output_exon_lengths \
    --output-circoplot $output_circo \
    --plot-abeta-region $plot_abeta


if [[ "$del_files" -eq "1" ]]; then
  echo -n "* Deleting temporary files..."
  rm $output_exon_lengths
  echo " OK."
fi
